//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ServerManager.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SERVERMANAGER_DIALOG        102
#define IDS_STRING102                   102
#define IDS_STRING103                   103
#define IDS_STRING104                   104
#define IDS_STRING105                   105
#define IDS_STRING106                   106
#define IDS_STRING107                   107
#define IDR_MAINFRAME                   128
#define IDB_LEDS                        130
#define IDR_MENU1                       131
#define ID_Menu                         132
#define ID_133                          133
#define ID_134                          134
#define IDB_STATEBITMAP                 135
#define IDB_BITMAP1                     136
#define IDR_SERVER_LIST_MENU            137
#define ID_CONTEXTMENU_OPEN             138
#define ID_CONTEXTMENU_MESSAGE          139
#define IDD_SERVERVIEW_DIALOG           141
#define IDB_PP_UNPINNEDEDGE             143
#define IDB_PP_PINNEDEDGE               144
#define IDB_PP_UNPINNED                 145
#define IDB_PP_PINNED                   146
#define IDB_MATRIXTINY                  147
#define IDB_MATRIXSMALL                 148
#define IDB_MATRIXLARGE                 149
#define IDD_DLG_MESSAGE                 150
#define IDD_DLG_JOB_SCHEDULE            153
#define IDD_DLG_JOB_BROADCAST_MESSAGE   154
#define IDR_SERVER_JOB_MENU             157
#define IDD_SVERSTATE_DIALOG            160
#define IDR_241                         160
#define IDC_LIST_SERVER                 1001
#define IDC_IPADDRESS                   1002
#define IDC_BTN_CONNECT                 1003
#define IDC_EDIT_PORT                   1004
#define IDC_EDIT_CONSOLE                1005
#define IDC_LED1                        1006
#define IDC_EDIT_REFRESH_RATE           1007
#define IDC_BUTTON1                     1008
#define IDC_EDIT_DIALOGUE_BASIC_TALK    1008
#define IDC_BTN_PIN                     1009
#define IDC_STATIC_USER                 1011
#define IDC_STATIC_RAM                  1012
#define IDC_STATIC_MAX                  1016
#define IDC_STATIC_CRT                  1017
#define IDC_STATIC_HISTO                1018
#define IDC_EDIT1                       1019
#define IDC_SMSTEST2                    1020
#define IDC_BTN_JOB_SCHEDULE            1021
#define IDC_LIST_JOB                    1022
#define IDC_COMBO_HOUR                  1024
#define IDC_COMBO_MIN                   1025
#define IDC_COMBO_TYPE                  1026
#define IDC_COMBO_GROUP                 1027
#define IDC_COMBO_NUMBER                1028
#define IDC_EDIT_BROADCAST_MESSAGE      1029
#define IDC_BTN_BROADCAST_MESSAGE_ADD   1030
#define IDC_BTN_MSG_SND                 1031
#define IDC_BUTTON4                     1033
#define IDC_COMBO1                      1034
#define IDC_COMBO_SERVER_LIST           1034
#define IDC_EDIT_MSG2                   1034
#define IDC_EDIT_MSG3                   1035
#define IDC_EDIT_MSG4                   1036
#define IDC_EDIT_MSG5                   1037
#define IDC_SEND_TYPE1                  1038
#define IDC_SEND_TYPE2                  1039
#define IDC_SVR_GROUP_CHECK1            1039
#define IDC_SVR_GROUP_CHECK2            1040
#define IDC_EDIT_MSG6                   1040
#define IDC_SVR_GROUP_CHECK3            1041
#define IDC_EDIT_MSG7                   1041
#define IDC_SVR_GROUP_CHECK4            1042
#define IDC_EDIT_MSG8                   1042
#define IDC_SVR_GROUP_CHECK5            1043
#define IDC_EDIT_MSG9                   1043
#define IDC_SVR_GROUP_CHECK6            1044
#define IDC_EDIT_MSG10                  1044
#define IDC_SVR_GROUP_CHECK7            1045
#define IDC_MONTHCALENDAR1              1045
#define IDC_EDIT_MSG12                  1045
#define IDC_SVR_GROUP_CHECK8            1046
#define IDC_SCH_EXPORT                  1046
#define IDC_EDIT_MSG13                  1046
#define IDC_SVR_CHECK1                  1047
#define IDC_SCH_IMPORT                  1047
#define IDC_SVR_CHECK2                  1048
#define IDC_SVR_CHECK3                  1049
#define IDC_SVR_CHECK4                  1050
#define IDC_SVR_CHECK5                  1051
#define IDC_SVR_CHECK6                  1052
#define IDC_SVR_CHECK7                  1053
#define IDC_SVR_CHECK8                  1054
#define IDC_EDIT_MSG14                  1055
#define IDC_EDIT_MSG1                   1056
#define IDC_EDIT_MSG                    1057
#define IDC_EDIT_MSG11                  1057
#define IDC_EDIT_MSG15                  1058
#define IDC_EDIT_MSG16                  1059
#define IDC_EDIT_MSG17                  1060
#define IDC_EDIT_MSG18                  1061
#define IDC_EDIT_MSG19                  1062
#define IDC_EDIT_MSG20                  1063
#define IDC_VIEW10_BUTTON               1064
#define IDC_VIEW20_BUTTON               1065
#define IDC_VIEW1_BUTTON                1066
#define IDC_SVRSTATE_BUTTON             1067
#define IDC_STATIC_MAX1                 1068
#define IDC_STATIC_CRT1                 1069
#define IDC_TRACING_BUTTON              1069
#define IDC_LIST_TRACING                1070
#define IDC_ADD_BUTTON                  1071
#define IDC_STATIC_MAX2                 1072
#define IDC_DEL_BUTTON                  1072
#define IDC_STATIC_CRT2                 1073
#define IDC_TRACING_EDIT                1073
#define IDC_STATIC_MAX3                 1074
#define IDC_STATIC_CRT3                 1075
#define IDC_STATIC_MAX4                 1076
#define IDC_STATIC_CRT4                 1077
#define IDC_STATIC_MAX5                 1078
#define IDC_ADD_TYPE_CHECK              1078
#define IDC_STATIC_CRT5                 1079
#define IDC_BTN_MSG_CLEAR               1079
#define IDC_STATIC_MAX6                 1080
#define IDC_STATIC_CRT6                 1081
#define IDC_STATIC_MAX7                 1082
#define IDC_STATIC_CRT7                 1083
#define IDC_STATIC_MAX8                 1084
#define IDC_STATIC_CRT8                 1085
#define IDC_STATIC_SVRNUM1              1087
#define IDC_STATIC_SVRNUM2              1095
#define IDC_STATIC_SVRNUM3              1096
#define IDC_STATIC_SVRNUM4              1097
#define IDC_STATIC_SVRNUM5              1098
#define IDC_STATIC_SVRNUM6              1099
#define IDC_STATIC_SVRNUM7              1100
#define IDC_STATIC_SVRNUM8              1101
#define ID_CONTEXTMENU_STOP             32772
#define ID_CONTEXTMENU_PAUSE            32773
#define ID_CONTEXTMENU_RESUME           32775
#define ID_CONTEXTMENU_PAUSE_5          32777
#define ID_CONTEXTMENU_RESTART          32778
#define ID_CONTEXTMENU_STOP_5           32780
#define ID_CONTEXTMENU_RESTART_5        32782
#define ID_JOB_EDIT                     32787
#define ID_JOB_DELETE                   32788
#define ID_JOB_ADD                      32789

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        161
#define _APS_NEXT_COMMAND_VALUE         32790
#define _APS_NEXT_CONTROL_VALUE         1080
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
