//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RanEditLevel.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_DLG_MAIN                    101
#define IDD_DLG_LIST_CROW               102
#define IDR_MAINFRAME                   128
#define IDR_RanEditLevelTYPE            129
#define IDD_DIALOG_MAIN                 130
#define IDD_DLG_BASIC                   131
#define IDD_DLG_CROWLIST                132
#define IDD_DLG_DUMMY                   133
#define IDD_DLG_CROWEDIT                134
#define IDD_DLG_CONDITION               135
#define IDD_DLG_GATELIST                136
#define IDD_DLG_EFFLIST                 137
#define IDD_DLG_LIST_ITEM               138
#define IDD_DLG_LIST_SKILL              139
#define IDD_DLG_LIST_QUEST              140
#define IDD_DLG_ETCHFUNCTION            141
#define IDD_DLG_LANDMARKLIST            142
#define IDD_DLG_GATEEDIT                143
#define IDD_DLG_LIST_MAP                144
#define IDD_DLG_EFFEDIT                 145
#define IDD_DLG_LANDMARKEDIT            146
#define IDD_DIALOG_CROW_REPLACE         147
#define IDD_DIALOG_CROW_REPLACE_MULTI   148
#define IDC_TREE                        1002
#define IDC_COMBO_PAGES                 1006
#define IDC_BUTTON_PAGESEL              1007
#define IDC_EDIT_BASIC_FILENAME         1008
#define IDC_EDIT_BASIC_WLDNAME          1009
#define IDC_BUTTON_BASIC_WLDOPEN        1010
#define IDC_COMBO_BASIC_QUAD            1011
#define IDC_BUTTON_BASIC_BUILDQUAD      1012
#define IDC_BUTTON_BASIC_SAVE           1013
#define IDC_BUTTON_BASIC_BACK           1014
#define IDC_BUTTON_BASIC_CANCEL         1014
#define IDC_BUTTON_BASIC_CLOSE          1014
#define IDC_EDIT_BASIC_DEVISION         1015
#define IDC_BUTTON_BASIC_APPLY          1015
#define IDC_BUTTON_CROWLIST_NEW         1016
#define IDC_BUTTON_BASIC_REGISTERNEWEFF 1016
#define IDC_BUTTON_BASIC_REG            1016
#define IDC_BUTTON_CROWLIST_DELETE      1017
#define IDC_EDIT_CROWNAME               1017
#define IDC_BUTTON_CROWLIST_EDIT        1018
#define IDC_EDIT_CROWMID                1019
#define IDC_BUTTON_CROWLIST_COPY        1019
#define IDC_EDIT_CROWSID                1020
#define IDC_BUTTON_CROWLIST_PASTENEW    1020
#define IDC_EDIT_CROWREALNAME           1021
#define IDC_EDIT_CROW_REGENTIME         1022
#define IDC_EDIT_CROW_REGENMIN          1023
#define IDC_EDIT_CROW_REGENHOUR         1024
#define IDC_CHECK_DAYOFWEEK_0           1025
#define IDC_CHECK_DAYOFWEEK_1           1026
#define IDC_CHECK_DAYOFWEEK_2           1027
#define IDC_CHECK_DAYOFWEEK_3           1028
#define IDC_CHECK_DAYOFWEEK_4           1029
#define IDC_CHECK_DAYOFWEEK_5           1030
#define IDC_CHECK_DAYOFWEEK_6           1031
#define IDC_EDIT_CROW_GROUP             1032
#define IDC_EDIT_CROW_BUSLOCATION       1033
#define IDC_CHECK_GROUPLEADER           1034
#define IDC_EDIT_CROW_REVIVEGATE        1035
#define IDC_CHECK_CROW_RANDOMPOS        1036
#define IDC_EDIT_CROW_RANDOMGEN_POSNUM  1037
#define IDC_EDIT_CROW_RANDOMGEN_POSDIST 1038
#define IDC_BUTTON_CROW                 1039
#define IDC_LIST_CROWACTION             1040
#define IDC_BUTTON_SCHED_ADD            1041
#define IDC_BUTTON_OPENBUSLOC           1042
#define IDC_BUTTON_SCHED_EDIT           1043
#define IDC_BUTTON_SCHED_DEL            1044
#define IDC_BUTTON_MOD_MAT              1045
#define IDC_BUTTON_MOD_MAT2             1046
#define IDC_BUTTON_REGISTER             1047
#define IDC_EDIT_CROW_MAT_X             1048
#define IDC_EDIT_CROW_MAT_Y             1049
#define IDC_EDIT_CROW_MAT_Z             1050
#define IDC_EDIT_CROW_MAT_NUM           1051
#define IDC_EDIT_CROW_MAT_TIME          1052
#define IDC_COMBO_MAT_TYPE              1053
#define IDC_BUTTON_ACTION_OK            1054
#define IDC_BUTTON_POS_GET              1055
#define IDC_BUTTON_LIST_OK              1056
#define IDC_BUTTON_APPLY                1056
#define IDC_BUTTON_LIST_CANCEL          1057
#define IDC_EDIT_LIST_MID               1058
#define IDC_EDIT_LIST_SID               1059
#define IDC_COMBO_REQ_SIGN_LEVEL        1059
#define IDC_EDIT_LIST_NAME              1060
#define IDC_EDIT_REQ_LEVEL1             1060
#define IDC_EDIT_REQ_LEVEL2             1061
#define IDC_EDIT_REQ_SKILL_MID          1062
#define IDC_EDIT_REQ_SKILL_SID          1063
#define IDC_EDIT_REQ_SKILL_NAME         1064
#define IDC_EDIT_REQ_ITEM_MID           1065
#define IDC_EDIT_REQ_ITEM_SID           1066
#define IDC_LIST_CROW                   1067
#define IDC_EDIT_REQ_ITEM_NAME          1067
#define IDC_EDIT_REQ_COMQUEST_MID       1068
#define IDC_EDIT_REQ_COMQUEST_SID       1069
#define IDC_EDIT_REQ_COMQUEST_NAME      1070
#define IDC_EDIT_REQ_ACTQUEST_MID       1071
#define IDC_EDIT_REQ_ACTQUEST_SID       1072
#define IDC_EDIT_REQ_ACTQUEST_NAME      1073
#define IDC_COMBO_REQ_SIGN_LIVING       1074
#define IDC_COMBO_REQ_SIGN_BRIGHT       1075
#define IDC_EDIT_REQ_LIVING             1076
#define IDC_EDIT_REQ_BRIGHT             1077
#define IDC_BUTTON_REQ_LEVEL            1078
#define IDC_BUTTON_REQ_ITEM             1079
#define IDC_BUTTON_REQ_SKILL            1080
#define IDC_BUTTON_REQ_COMQUEST         1081
#define IDC_BUTTON_REQ_ACTQUEST         1082
#define IDC_BUTTON_REQ_LIVING           1083
#define IDC_BUTTON_REQ_BRIGHT           1084
#define IDC_CHECK_REQ_PARTYMEMBER       1085
#define IDC_BUTTON_NAME_CHECK           1086
#define IDC_BUTTON_NAME_NEW             1087
#define IDC_EDIT_COPY                   1087
#define IDC_CHECK_USE_FUNC_0            1088
#define IDC_CHECK_USE_FUNC_1            1089
#define IDC_CHECK_USE_FUNC_2            1090
#define IDC_COMBO_REQ_SIGN_REBORN       1090
#define IDC_CHECK_USE_FUNC_3            1091
#define IDC_EDIT_REQ_REBORN1            1091
#define IDC_CHECK_USE_FUNC_4            1092
#define IDC_EDIT_REQ_REBORN2            1092
#define IDC_CHECK_USE_FUNC_5            1093
#define IDC_BUTTON_REQ_LEVEL2           1093
#define IDC_BUTTON_REQ_REBORN           1093
#define IDC_EDIT_ETC_LIMITTIME          1094
#define IDC_EDIT_ETC_LIMITTIMETERM      1095
#define IDC_EDIT_ETC_UP                 1096
#define IDC_EDIT_ETC_DOWN               1097
#define IDC_EDIT_ETC_LEFT               1098
#define IDC_EDIT_ETC_RIGHT              1099
#define IDC_EDIT_ETC_FAR                1100
#define IDC_EDIT_ETC_NEAR               1101
#define IDC_EDIT_ETC_POS_X              1102
#define IDC_EDIT_ETC_POS_Y              1103
#define IDC_EDIT_ETC_POS_Z              1104
#define IDC_BUTTON_ETCH_CAPTURE_CAM     1105
#define IDC_LIST_LANDEFF                1106
#define IDC_BUTTON_DEL_ITEM             1107
#define IDC_BUTTON_DEL_SKILL            1108
#define IDC_BUTTON_DEL_COMQUEST         1109
#define IDC_BUTTON_ETC_EFF_ADD          1109
#define IDC_BUTTON_DEL_ACTQUEST         1110
#define IDC_BUTTON_ETC_EFF_EDIT         1110
#define IDC_BUTTON_ETC_EFF_DEL          1111
#define IDC_COMBO_ETCH_EFF_TYPE         1112
#define IDC_EDIT_ETCH_EFF_VAR           1113
#define IDC_EDIT_ETCH_EFF_MIN_X         1114
#define IDC_EDIT_ETCH_EFF_MIN_Y         1115
#define IDC_EDIT_ETCH_EFF_MAX_X         1116
#define IDC_EDIT_ETCH_EFF_MAX_Y         1117
#define IDC_BUTTON_ETCH_EFF_OK          1118
#define IDC_EDIT_ETCH_EFFLIST_NUM       1119
#define IDC_BUTTON_ETCH_EFF_POS_EDIT    1120
#define IDC_BUTTON_ETCH_EFF_POS_SAVE    1121
#define IDC_BUTTON_ETCH_EFF_POS_GET     1122
#define IDC_BUTTON_ETCH_EFF_CANCEL      1123
#define IDC_LIST_GATE                   1123
#define IDC_LIST_EFF                    1124
#define IDC_LIST_LANDMARK               1125
#define IDC_BUTTON_GATE_ADD             1126
#define IDC_BUTTON_GATE_EDIT            1127
#define IDC_EDIT_GATE_NAME              1127
#define IDC_BUTTON_GATE_DEL             1128
#define IDC_CHECK_GATE_IN               1128
#define IDC_CHECK_GATE_OUT              1129
#define IDC_EDIT_GATE_ID                1130
#define IDC_EDIT_GATE_TOMAP_MID         1131
#define IDC_EDIT_GATE_TOMAP_SID         1132
#define IDC_EDIT_GATE_TOMAP_NAME        1133
#define IDC_BUTTON_GATE_TOMAP           1134
#define IDC_EDIT_GATE_TOGATEID          1135
#define IDC_EDIT_GATE_DIV_X             1136
#define IDC_EDIT_GATE_DIV_Y             1137
#define IDC_LIST_MAP                    1137
#define IDC_BUTTON_GATE_NAME_CHECK      1138
#define IDC_BUTTON_GATE_NAME_NEW        1139
#define IDC_BUTTON_GATE_REGNEW          1140
#define IDC_EDIT_GATE_MIN_X             1141
#define IDC_EDIT_GATE_MIN_Y             1142
#define IDC_EDIT_GATE_MAX_X             1143
#define IDC_EDIT_GATE_MAX_Y             1144
#define IDC_EDIT_GATE_MIN_Z             1145
#define IDC_BUTTON_GATE_MAT_EDIT        1146
#define IDC_EDIT_GATE_MAX_Z             1147
#define IDC_BUTTON_EFF_ADD              1147
#define IDC_BUTTON_GATE_MAT_SAVE        1148
#define IDC_BUTTON_EFF_EDIT             1148
#define IDC_EDIT_EFF_FILENAME           1148
#define IDC_BUTTON_GATE_MAT_SCREENPOS   1149
#define IDC_BUTTON_EFF_DEL              1149
#define IDC_BUTTON_EFF_OPEN             1149
#define IDC_BUTTON_GATE_ID_CHECK        1150
#define IDC_EDIT_EFF_NAME               1150
#define IDC_BUTTON_GATE_ID_NEW          1151
#define IDC_BUTTON_EFF_EDITMAT          1151
#define IDC_BUTTON_EFF_MATNEW           1152
#define IDC_BUTTON_EDIT_EFFMATRIX_CANCEL 1153
#define IDC_BUTTON_LM_ADD               1155
#define IDC_BUTTON_LM_DEL               1156
#define IDC_EDIT_LM_NAME                1156
#define IDC_BUTTON_LM_EDIT              1157
#define IDC_BUTTON_LM_NAME_CHECK        1157
#define IDC_BUTTON_LM_NAME_NEW          1158
#define IDC_BUTTON_LM_POS_EDIT          1159
#define IDC_BUTTON_LM_POS_SAVE          1160
#define IDC_BUTTON_LM_POS_NEW           1161
#define IDC_BUTTON_LM_POS_NEW2          1162
#define IDC_BUTTON_LM_POS_REBUILD       1162
#define IDC_EDIT_MID_FROM               1163
#define IDC_EDIT_SID_FROM               1164
#define IDC_EDIT_MID_TO                 1165
#define IDC_EDIT_SID_TO                 1166
#define IDC_EDIT_VMAX_Z                 1167
#define IDC_EDIT_CROW                   1167
#define IDC_BUTTON_REPLACE_ID           1169
#define IDC_BUTTON_REFRESH              1171
#define IDC_EDIT_FILTER_MID             1172
#define IDC_EDIT_FILTER_SID             1173
#define IDC_BUTTON_REMOVEFILTER         1174
#define IDC_BUTTON_ADD                  1176
#define IDC_LIST_REPLACE                1177
#define IDC_BUTTON_REPLACE_ID2          1178
#define IDC_BUTTON_DELETE               1179
#define IDC_BUTTON_DELETE2              1180
#define IDC_BUTTON_SHOW_INVALID         1180
#define IDC_BUTTON1                     1181
#define IDC_BUTTON_SHOWNPC              1181
#define ID_VIEW_EDITTOOLBAR             32771
#define ID_VIEW_RESETCAMERAPOS          32775
#define ID_DEVLORDX                     32776
#define ID_CAMERACONTROLS_RESETCAMERAPOS 32777
#define ID_CAMERACONTROLS_CAMERASPEED300 32778
#define ID_CAMERACONTROLS_CAMERASPEED600 32779
#define ID_CAMERACONTROLS_CAMERASPEED900 32780
#define ID_RENDEROPTIONS_RENDERQUADTREE 32781
#define ID_RENDEROPTIONS_RENDERCROWMODELS 32782
#define ID_RENDEROPTIONS_RENDERCROWSCHEDULE 32783
#define ID_SKINCHAR_LOAD                32784
#define ID_SKINCHAR_APPLYPIECE          32785
#define ID_SKINCHAR_SETABL              32786
#define ID_SKINCHAR_SETVCF              32787
#define ID_SKINCHAR_CLEAR               32788
#define ID_SKINCHAR_DELETE              32789
#define ID_SKINCHAR_ANIMATEIDLE         32790
#define ID_RENDEROPTIONS_RENDERCROWSCHED 32791
#define ID_RENDEROPTIONS_RENDERDEBUGINFO 32792
#define ID_RENDEROPTIONS_RENDERGATE     32793
#define ID_RENDEROPTIONS_RENDERLANDEFFECT 32800
#define ID_WLD_WLDLOAD                  32801
#define ID_WLD_WLDSAVE                  32802
#define ID_WLD_WLDCLEAR                 32803
#define ID_MOUSECONTROL_MOVE            32804
#define ID_MOUSECONTROL_ROTATE          32805
#define ID_MOUSECONTROL_SCALE           32806
#define ID_MOUSECONTROL_DETECTOBJECT    32807
#define ID_MOUSECONTROL_NONE            32808
#define ID_MOUSECONTROL_BOXMOVE         32809
#define ID_MOUSECONTROL_BOXSCALE        32810
#define ID_MOUSECONTROL_BOXSELSCALE     32811
#define ID_RENDEROPTIONS_RENDERSPHERE   32812
#define ID_RENDEROPTIONS_RENDERCROWGENPOS 32813
#define ID_SOUND_BGMSOUND               32814
#define ID_SOUND_ENVSOUND               32815
#define ID_SOUND_SFXSOUND               32816
#define ID_MOUSECONTROL_EFFMATRIXMOVE   32817
#define ID_MOUSECONTROL_EFFMATRIXROTATE 32818
#define ID_MOUSECONTROL_EFFMATRIXSCALE  32819
#define ID_FILE_OPENEX                  32820

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         32821
#define _APS_NEXT_CONTROL_VALUE         1182
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
