//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RanTool.rc
//
#define IDD_RANTOOL_DIALOG              102
#define IDR_HTML_EFFSINGLE              103
#define IDD_ABF_DIALOG                  109
#define IDD_ABL_DIALOG                  110
#define IDD_CFG_DIALOG                  111
#define IDD_CHF_DIALOG                  112
#define IDD_VCF_DIALOG                  113
#define IDD_DEFAULT                     114
#define IDD_CNV_DIALOG                  115
#define IDD_PS_DIALOG                   116
#define IDD_CREDITS                     117
#define IDD_BASE                        118
#define IDR_MAINFRAME                   128
#define IDS_SHEET_CAPTION               129
#define IDR_241                         130
#define IDD_MMP_DIALOG                  137
#define IDD_CRY_DIALOG                  138
#define IDD_XSINGLE                     139
#define IDR_242                         139
#define IDD_XLIST                       140
#define IDR_243                         140
#define IDD_XBLANK                      141
#define IDD_XSHOCK_A                    141
#define IDD_XBLUR                       142
#define IDD_XCLONEBLUR                  143
#define IDB_XYZ                         143
#define IDD_XDUST                       144
#define IDD_XNONE                       145
#define IDD_XATTRI                      146
#define IDD_ZLIST                       147
#define IDD_ZSINGLE                     148
#define IDD_ZBLANK                      149
#define IDD_ZGHOSTING                   150
#define IDD_ZTRACE                      151
#define IDD_ZFACEOFF                    152
#define IDD_XARROW                      153
#define IDD_XSPECULAR                   154
#define IDD_XLEVEL                      155
#define IDD_XEMIT                       156
#define IDD_XALPHA                      157
#define IDD_XNEON                       158
#define IDD_XMARK                       159
#define IDD_XNOALPHA                    160
#define IDD_XREFLECTION2                161
#define IDD_XAMBIENT                    162
#define IDD_XDOT3                       163
#define IDD_XMULTITEX                   164
#define IDD_XGHOSTING                   165
#define IDD_XSPECULAR2                  166
#define IDD_XTOON                       167
#define IDD_XTEXDIFF                    168
#define IDD_XPARTICLE                   169
#define IDD_XBONEPOS                    170
#define IDD_XBONELIST                   171
#define IDD_XUSERCOLOR                  172
#define IDD_XNORMALMAP                  173
#define IDD_XLINE2BONE                  174
#define IDD_XNONE1                      175
#define IDD_XAROUND                     175
#define IDC_COMBO_TOOL                  1000
#define IDC_BUTTON_LOADABLNEO           1000
#define IDC_BUTTON_LOAD                 1000
#define IDC_CHECK_BWO                   1000
#define IDC_LOAD_BIN                    1000
#define IDC_BUTTON1                     1000
#define IDC_EDIT_OPEN                   1000
#define IDC_STATIC_TOOL                 1001
#define IDC_BUTTON_LOADABL              1001
#define IDC_BUTTON_SAVE                 1001
#define IDC_SAVE_BIN                    1001
#define IDC_LX                          1001
#define IDC_OPEN                        1001
#define IDC_BUTTON_RUN                  1002
#define IDC_BUTTON_SAVEABL              1002
#define IDC_EDIT_NAME                   1002
#define IDC_EDIT_LOAD_BIN               1002
#define IDC_TY                          1002
#define IDC_EDIT_SAVE                   1002
#define IDC_EDIT_TOOL                   1003
#define IDC_EDIT_ABFFILE                1003
#define IDC_EDIT_SKELNAME               1003
#define IDC_EDIT_SAVE_BIN               1003
#define IDC_RX                          1003
#define IDC_SAVE                        1003
#define IDC_EDIT_CPSFILE                1004
#define IDC_EDIT_ANIM                   1004
#define IDC_LOAD_CFG                    1004
#define IDC_BUTTON_ABOUT                1004
#define IDC_BY                          1004
#define IDC_ENCRYPT                     1004
#define IDC_EDIT_SKEFILE                1005
#define IDC_EDIT_DWSTIME                1005
#define IDC_SAVE_CFG                    1005
#define IDC_FILENAME                    1005
#define IDC_DECRYPT                     1005
#define IDC_EDIT_BONELINK               1006
#define IDC_EDIT_DWETIME                1006
#define IDC_EDIT_LOAD_CFG               1006
#define IDC_BUTTON2                     1006
#define IDC_REVERSE                     1006
#define IDC_COMBO_TYPE                  1007
#define IDC_EDIT_DWETIMEORIG            1007
#define IDC_EDIT_SAVE_CFG               1007
#define IDC_VIEW                        1007
#define IDC_MOD                         1007
#define IDC_MODE                        1007
#define IDC_EDIT_BONE_FILE              1008
#define IDC_COMBO_SLOT                  1008
#define IDC_EDIT_DWUNITTIME             1008
#define IDC_CHECK_SAVE                  1008
#define IDC_LOAD_EGP                    1008
#define IDC_HIDE                        1008
#define IDC_SAMEFILE                    1008
#define IDC_COMBO_PIECE0                1009
#define IDC_EDIT_NAMELOAD               1009
#define IDC_EDIT_FILENAME               1009
#define IDC_EDIT_DDS                    1009
#define IDC_TYPE                        1009
#define IDC_EDIT_ROTX                   1010
#define IDC_COMBO_ANISUB                1010
#define IDC_SAVE_EGP                    1010
#define IDC_EDIT_RESULT                 1010
#define IDC_EDIT_TRACE                  1010
#define IDC_CHECK_BCPS                  1011
#define IDC_EDIT_DIVCOUNT               1011
#define IDC_EDIT_UP                     1011
#define IDC_EDIT_BMP                    1011
#define IDC_EDIT_TRACEBACK              1011
#define IDC_EDIT_RESULT2                1011
#define IDC_EDIT_RESULT_ERR             1011
#define IDC_EDIT_DWFLAG                 1012
#define IDC_EDIT_DOWN                   1012
#define IDC_BUTTON_NEW                  1012
#define IDC_BUTTON_NEWABL               1012
#define IDC_EDIT_ROTY                   1013
#define IDC_EDIT_ANIS                   1013
#define IDC_EDIT_NAMESAVE               1013
#define IDC_EDIT_ROTZ                   1014
#define IDC_EDIT_DIV0                   1014
#define IDC_EDIT_CNVLOG                 1014
#define IDC_EDIT_ROOTX                  1015
#define IDC_EDIT_DIV1                   1015
#define IDC_EDIT_CNVLOGERR              1015
#define IDC_EDIT_ROOTY                  1016
#define IDC_EDIT_DIV2                   1016
#define IDC_EDIT_ROOTZ                  1017
#define IDC_EDIT_DIV3                   1017
#define IDC_EDIT_ROTXF                  1018
#define IDC_EDIT_DIV4                   1018
#define IDC_EDIT_ROTYF                  1019
#define IDC_EDIT_DIV5                   1019
#define IDC_EDIT_ROTZF                  1020
#define IDC_EDIT_DIV6                   1020
#define IDC_EDIT_ROOTXF                 1021
#define IDC_EDIT_DIV7                   1021
#define IDC_EDIT_ROOTYF                 1022
#define IDC_EDIT_DIV8                   1022
#define IDC_EDIT_ROOTZF                 1023
#define IDC_EDIT_STRIKECOUNT            1023
#define IDC_COMBO_PIECE1                1024
#define IDC_COMBO_PIECE2                1025
#define IDC_COMBO_PIECE3                1026
#define IDC_COMBO_PIECE4                1027
#define IDC_COMBO_PIECE5                1028
#define IDC_EDIT_HEAD                   1029
#define IDC_COMBO_PIECE6                1029
#define IDC_EDIT_HEAD_VCF               1029
#define IDC_COMBO_PIECE7                1030
#define IDC_EDIT_HEAD2                  1030
#define IDC_EDIT_BODY                   1031
#define IDC_COMBO_PIECE8                1031
#define IDC_EDIT_BODY_VCF               1031
#define IDC_COMBO_PIECE9                1032
#define IDC_EDIT_PANT                   1033
#define IDC_COMBO_EFF0                  1033
#define IDC_EDIT_PANT_VCF               1033
#define IDC_COMBO_EFF1                  1034
#define IDC_EDIT_GLOVE                  1035
#define IDC_COMBO_EFF2                  1035
#define IDC_EDIT_GLOVE_VCF              1035
#define IDC_COMBO_EFF3                  1036
#define IDC_EDIT_RHAND                  1037
#define IDC_COMBO_EFF4                  1037
#define IDC_EDIT_RHAND_VCF              1037
#define IDC_COMBO_EFF5                  1038
#define IDC_EDIT_LHAND                  1039
#define IDC_COMBO_EFF6                  1039
#define IDC_EDIT_LHAND_VCF              1039
#define IDC_COMBO_EFF7                  1040
#define IDC_EDIT_FOOT                   1041
#define IDC_COMBO_EFF8                  1041
#define IDC_EDIT_FOOT_VCF               1041
#define IDC_COMBO_EFF9                  1042
#define IDC_EDIT_HAIR                   1043
#define IDC_EDIT_SFRAME0                1043
#define IDC_EDIT_HAIR_VCF               1043
#define IDC_EDIT_SFRAME1                1044
#define IDC_EDIT_ACC                    1045
#define IDC_EDIT_SFRAME2                1045
#define IDC_EDIT_ACC_VCF                1045
#define IDC_EDIT_SFRAME3                1046
#define IDC_EDIT_VEHICLE                1047
#define IDC_EDIT_SFRAME4                1047
#define IDC_EDIT_VEHICLE_VCF            1047
#define IDC_EDIT_SFRAME5                1048
#define IDC_EDIT_NECK_VCF               1048
#define IDC_EDIT_WING                   1049
#define IDC_EDIT_SFRAME6                1049
#define IDC_EDIT_WING_VCF               1049
#define IDC_BUTTON_BODY                 1050
#define IDC_EDIT_SFRAME7                1050
#define IDC_BUTTON_BODY_VCF             1050
#define IDC_BUTTON_PANT                 1051
#define IDC_EDIT_SFRAME8                1051
#define IDC_BUTTON_PANT_VCF             1051
#define IDC_BUTTON_GLOVE                1052
#define IDC_EDIT_SFRAME9                1052
#define IDC_BUTTON_GLOVE_VCF            1052
#define IDC_BUTTON_RHAND                1053
#define IDC_COMBO_ANIMAIN               1053
#define IDC_BUTTON_RHAND_VCF            1053
#define IDC_BUTTON_LHAND                1054
#define IDC_EDIT_FRAMECOUNT             1054
#define IDC_BUTTON_LHAND_VCF            1054
#define IDC_BUTTON_FOOT                 1055
#define IDC_EDIT_SOUND0                 1055
#define IDC_BUTTON_FOOT_VCF             1055
#define IDC_BUTTON_HAIR                 1056
#define IDC_EDIT_SOUND1                 1056
#define IDC_BUTTON_HAIR_VCF             1056
#define IDC_BUTTON_ACC                  1057
#define IDC_EDIT_SOUND2                 1057
#define IDC_BUTTON_ACC_VCF              1057
#define IDC_BUTTON_VEHICLE              1058
#define IDC_EDIT_SOUND3                 1058
#define IDC_BUTTON_VEHICLE_VCF          1058
#define IDC_BUTTON_WING                 1059
#define IDC_EDIT_SOUND4                 1059
#define IDC_BUTTON_WING_VCF             1059
#define IDC_BUTTON_HEAD                 1060
#define IDC_EDIT_SOUND5                 1060
#define IDC_BUTTON_HEAD_VCF             1060
#define IDC_LIST_ANI                    1061
#define IDC_EDIT_SOUND6                 1061
#define IDC_BUTTON_ANILIST_ADD          1062
#define IDC_EDIT_SOUND7                 1062
#define IDC_BUTTON_ANILIST_DELETE       1063
#define IDC_EDIT_SOUND8                 1063
#define IDC_EDIT_ANILIST_NAME           1064
#define IDC_EDIT_SOUND9                 1064
#define IDC_BUTTON_ANILIST_EDIT         1065
#define IDC_CHECK_LOOP0                 1065
#define IDC_BUTTON_ANILIST_OK           1066
#define IDC_CHECK_LOOP1                 1066
#define IDC_LIST_BONE                   1067
#define IDC_CHECK_LOOP2                 1067
#define IDC_BUTTON_BONELIST_ADD         1068
#define IDC_CHECK_LOOP3                 1068
#define IDC_BUTTON_BONELIST_DEL         1069
#define IDC_CHECK_LOOP4                 1069
#define IDC_CHECK_LOOP5                 1070
#define IDC_BUTTON_HEAD2                1070
#define IDC_EDIT_WRIST_VCF              1070
#define IDC_BUTTON_ANILIST_FOLDER       1070
#define IDC_EDIT_BONE1                  1071
#define IDC_CHECK_LOOP6                 1071
#define IDC_EDIT_BONE2                  1072
#define IDC_CHECK_LOOP7                 1072
#define IDC_EDIT_BONE3                  1073
#define IDC_CHECK_LOOP8                 1073
#define IDC_EDIT_BONE_NAME              1074
#define IDC_CHECK_LOOP9                 1074
#define IDC_BUTTON_BONELIST_EDIT        1075
#define IDC_EDIT_PFRAME0                1075
#define IDC_BUTTON_BONELIST_OK          1076
#define IDC_EDIT_PFRAME1                1076
#define IDC_EDIT_PFRAME2                1077
#define IDC_EDIT_RFINGER_VCF            1077
#define IDC_BUTTON_BONELIST_CAN         1077
#define IDC_EDIT_SCALE                  1078
#define IDC_EDIT_PFRAME3                1078
#define IDC_EDIT_HEIGHT                 1079
#define IDC_EDIT_PFRAME4                1079
#define IDC_BUTTON_BONELIST_CANCEL      1079
#define IDC_EDIT_DEPTHUP                1079
#define IDC_EDIT_RADIUS                 1080
#define IDC_EDIT_PFRAME5                1080
#define IDC_EDIT_DEPTHDOWN              1080
#define IDC_BUTTON_ANILIST_FOLDER2      1080
#define IDC_EDIT_MIN_X                  1081
#define IDC_EDIT_PFRAME6                1081
#define IDC_EDIT_REPEATSPEED            1081
#define IDC_EDIT_MIN_Y                  1082
#define IDC_EDIT_PFRAME7                1082
#define IDC_EDIT_MIN_Z                  1083
#define IDC_EDIT_PFRAME8                1083
#define IDC_EDIT_MAX_X                  1084
#define IDC_EDIT_PFRAME9                1084
#define IDC_EDIT_MAX_Y                  1085
#define IDC_EDIT_PFRAME10               1085
#define IDC_EDIT_MAX_Z                  1086
#define IDC_EDIT_FILENAME2              1086
#define IDC_BUTTON_ABF_SAVE             1087
#define IDC_BUTTON_ABF_LOAD             1088
#define IDC_BUTTON_VCF_SAVE             1088
#define IDC_EDIT_SECOND_ROT_X           1089
#define IDC_BUTTON_CPS_LOAD             1089
#define IDC_BUTTON_NECK_CHF             1089
#define IDC_BUTTON_ABF_LOAD2            1089
#define IDC_EDIT_SECOND_ROT_Y           1090
#define IDC_BUTTON_CPS_SAVE             1090
#define IDC_BUTTON_WRIST_CHF            1090
#define IDC_EDIT_SECOND_ROT_Z           1091
#define IDC_BUTTON_RFINGER_CHF          1091
#define IDC_BUTTON_CPS_LOADRAN2         1091
#define IDC_EDIT_SECOND_POS_X           1092
#define IDC_EDIT_SKELETON               1092
#define IDC_EDIT_LFINGER_CHF            1092
#define IDC_EDIT_SECOND_POS_Y           1093
#define IDC_EDIT_SKIN                   1093
#define IDC_EDIT_SECOND_POS_Z           1094
#define IDC_EDIT_MESH                   1094
#define IDC_EDIT_FIRST_ROT_X            1095
#define IDC_COMBO_PIECE                 1095
#define IDC_EDIT_AURA_CHF               1095
#define IDC_EDIT_FILER                  1095
#define IDC_EDIT_FIRST_ROT_Y            1096
#define IDC_COMBO_WEPBACK               1096
#define IDC_EDIT_BELT_CHF               1096
#define IDC_EDIT_FILEC                  1096
#define IDC_EDIT_FIRST_ROT_Z            1097
#define IDC_EDIT_EAR_CHF                1097
#define IDC_BUTTON_CPS_NEW              1097
#define IDC_EDIT_FIRST_POS_X            1098
#define IDC_EDIT_REF                    1098
#define IDC_EDIT_ACCE_CHF               1098
#define IDC_EDIT_FIRST_POS_Y            1099
#define IDC_EDIT_FLAG                   1099
#define IDC_EDIT_CON_CHF                1099
#define IDC_EDIT_FIRST_POS_Z            1100
#define IDC_LIST_MATERIAL               1100
#define IDC_EDIT_SECOND_STR             1101
#define IDC_MAT_EDIT                    1101
#define IDC_EDIT_FIRST_STR              1102
#define IDC_MAT_ADD                     1102
#define IDC_BUTTON_CHF_SAVE             1103
#define IDC_BUTTON_VCF_LOAD             1103
#define IDC_MAT_DEL                     1103
#define IDC_BUTTON_ACCE_ABF             1103
#define IDC_BUTTON_ANILIST_SEARCH       1104
#define IDC_EDIT_MATNUM                 1104
#define IDC_BUTTON_CHF_LOAD             1105
#define IDC_MAT_OK                      1105
#define IDC_BUTTON_CON_ABF              1105
#define IDC_BUTTON_NECK_VCF             1105
#define IDC_MAT_CANCEL                  1106
#define IDC_BUTTON_ACCE_CHF             1106
#define IDC_BUTTON_WRIST_VCF            1106
#define IDC_EDIT_MAT_TEX                1107
#define IDC_BUTTON_CON_CHF              1107
#define IDC_BUTTON_RFINGER_VCF          1107
#define IDC_EDIT_MAT_FLAG               1108
#define IDC_BUTTON_LFINGER_VCF          1108
#define IDC_BUTTON_CHF_SAVE2            1108
#define IDC_EDIT_MAT_BIAS               1109
#define IDC_EDIT_LFINGER_VCF            1109
#define IDC_BUTTON_CHF_NEW              1109
#define IDC_LIST_EFFECT                 1110
#define IDC_BUTTON_CHF_NEW2             1110
#define IDC_LIST_TRACE                  1111
#define IDC_EDIT_AURA_VCF               1111
#define IDC_EFF_DEL                     1112
#define IDC_EFF_ADD                     1113
#define IDC_EDIT_BELT_VCF               1113
#define IDC_EFF_EDIT                    1114
#define IDC_TRACE_ADD                   1115
#define IDC_EDIT_EAR_VCF                1115
#define IDC_EFF_CLEAR                   1115
#define IDC_TRACE_EDIT                  1116
#define IDC_BUTTON_ACCE_VCF             1116
#define IDC_EFF_COPY                    1116
#define IDC_TRACE_DEL                   1117
#define IDC_BUTTON_CON_VCF              1117
#define IDC_EDIT_T_NAME                 1118
#define IDC_EDIT_ACCE_VCF               1118
#define IDC_LIST_TRACE_BONE             1119
#define IDC_EDIT_CON_VCF                1119
#define IDC_EDIT_T_INDEX                1120
#define IDC_EDIT_T_VEC_X                1121
#define IDC_EDIT_T_VEC_Y                1122
#define IDC_EDIT_T_VEC_Z                1123
#define IDC_EDIT_T_NOR_X                1124
#define IDC_EDIT_T_NOR_Y                1125
#define IDC_EDIT_T_NOR_Z                1126
#define IDC_EDIT_T_W                    1127
#define IDC_EDIT_T_B                    1128
#define IDC_EFF_T_ADD                   1129
#define IDC_EFF_T_EDIT                  1130
#define IDC_EFF_T_DEL                   1131
#define IDC_EDIT_T_NUM                  1132
#define IDC_EFF_T_OK                    1133
#define IDC_EFF_T_CAN                   1134
#define IDC_TRACE_OK                    1135
#define IDC_TRACE_CAN                   1136
#define IDC_BUTTON_AURA_VCF             1136
#define IDC_BUTTON_BELT_VCF             1137
#define IDC_EFF_SELECT                  1137
#define IDC_BUTTON_EAR_VCF              1138
#define IDC_EFF_CANCEL                  1138
#define IDC_BUTTON_LFINGER_CHF          1139
#define IDC_EDIT_HEAD_ABF               1140
#define IDC_EDIT_BODY_ABF               1141
#define IDC_EDIT_PANT_ABF               1142
#define IDC_EDIT_FOOT_ABF               1143
#define IDC_EDIT_GLOVE_ABF              1144
#define IDC_EDIT_RHAND_ABF              1145
#define IDC_EDIT_LHAND_ABF              1146
#define IDC_EDIT_HAIR_ABF               1147
#define IDC_EDIT_ACC_ABF                1148
#define IDC_EDIT_VEHICLE_ABF            1149
#define IDC_EDIT_NECK_ABF               1150
#define IDC_EDIT_WRIST_ABF              1151
#define IDC_EDIT_RFINGER_ABF            1152
#define IDC_EDIT_LFINGER_ABF            1153
#define IDC_EDIT_WING_ABF               1154
#define IDC_LIST_ANIEFF                 1155
#define IDC_EDIT_AURA_ABF               1155
#define IDC_EDIT_BELT_ABF               1156
#define IDC_EDIT_EAR_ABF                1157
#define IDC_EDIT_ACCE_ABF               1158
#define IDC_EDIT_CON_ABF                1159
#define IDC_BUTTON_EAR_ABF              1160
#define IDC_BUTTON_BELT_ABF             1161
#define IDC_BUTTON_AURA_ABF             1162
#define IDC_BUTTON_WING_ABF             1163
#define IDC_BUTTON_LFINGER_ABF          1164
#define IDC_BUTTON_RFINGER_ABF          1165
#define IDC_BUTTON_WRIST_ABF            1166
#define IDC_BUTTON_NECK_ABF             1167
#define IDC_BUTTON_VEHICLE_ABF          1168
#define IDC_BUTTON_ACC_ABF              1169
#define IDC_BUTTON_HAIR_ABF             1170
#define IDC_BUTTON_LHAND_ABF            1171
#define IDC_BUTTON_RHAND_ABF            1172
#define IDC_BUTTON_GLOVE_ABF            1173
#define IDC_BUTTON_FOOT_ABF             1174
#define IDC_BUTTON_PANT_ABF             1175
#define IDC_BUTTON_BODY_ABF             1176
#define IDC_BUTTON_HEAD_ABF             1177
#define IDC_BUTTON_HEAD_CHF             1178
#define IDC_EDIT_HEAD_CHF               1179
#define IDC_BUTTON_BODY_CHF             1180
#define IDC_EDIT_BODY_CHF               1181
#define IDC_BUTTON_PANT_CHF             1182
#define IDC_EDIT_PANT_CHF               1183
#define IDC_BUTTON_FOOT_CHF             1184
#define IDC_EDIT_FOOT_CHF               1185
#define IDC_BUTTON_GLOVE_CHF            1186
#define IDC_BUTTON_RHAND_CHF            1187
#define IDC_BUTTON_LHAND_CHF            1188
#define IDC_BUTTON_HAIR_CHF             1189
#define IDC_BUTTON_ACC_CHF              1190
#define IDC_BUTTON_VEHICLE_CHF          1191
#define IDC_BUTTON_WING_CHF             1192
#define IDC_BUTTON_AURA_CHF             1193
#define IDC_BUTTON_BELT_CHF             1194
#define IDC_BUTTON_EAR_CHF              1195
#define IDC_EDIT_GLOVE_CHF              1196
#define IDC_EDIT_RHAND_CHF              1197
#define IDC_EDIT_LHAND_CHF              1198
#define IDC_EDIT_HAIR_CHF               1199
#define IDC_EDIT_ACC_CHF                1200
#define IDC_EDIT_VEHICLE_CHF            1201
#define IDC_EDIT_NECK_CHF               1202
#define IDC_EDIT_WRIST_CHF              1203
#define IDC_EDIT_RFINGER_CHF            1204
#define IDC_EDIT_WING_CHF               1205
#define IDC_COMBO_EFFECT                1206
#define IDC_STATIC_EFFECT               1207
#define IDC_BUTTON_OK                   1208
#define IDC_BUTTON_CANCEL               1209
#define IDC_CHECK_REPEAT                1210
#define IDC_CHECK_REPEATMOVE            1211
#define IDC_CHECK_AUTOMOVE              1212
#define IDC_CHECK_1POINT                1213
#define IDC_CHECK_2POINT                1214
#define IDC_CHECK_MATRIX                1215
#define IDC_EDIT_PLAYSINGLE             1216
#define IDC_COMBO_WEATHER               1217
#define IDC_COMBO_ANIM                  1218
#define IDC_EDIT_COOLTIME               1219
#define IDC_CHECK_NOUSEORIGIN           1220
#define IDC_CHECK_USEREFRACT            1221
#define IDC_CHECK_NOUSEBEZIER           1222
#define IDC_CHECK_NOUSEMIDDLE           1223
#define IDC_CHECK_USEALLACTION          1224
#define IDC_EDIT_BLEND                  1225
#define IDC_EDIT_FULLLIFE               1226
#define IDC_EDIT_CBLEND                 1226
#define IDC_EDIT_SEC                    1226
#define IDC_EDIT_TEXNUM                 1226
#define IDC_EDIT_VCOLORUP1              1227
#define IDC_EDIT_SETRATE                1227
#define IDC_EDIT_VCOLORUP2              1228
#define IDC_EDIT_VCOLORUP3              1229
#define IDC_EDIT_VCOLORUP4              1230
#define IDC_EDIT_VCOLORDN1              1231
#define IDC_EDIT_VCOLORDN2              1232
#define IDC_EDIT_VCOLORDN3              1233
#define IDC_EDIT_VCOLORDN4              1234
#define IDC_COMBO_ANIM_M                1235
#define IDC_COMBO_ANIM_S                1236
#define IDC_EDIT_TEX                    1237
#define IDC_EDIT_TRACEUP                1238
#define IDC_CHECK_USE                   1238
#define IDC_EDIT_TRACEDN                1239
#define IDC_CHECK_BEZIER                1239
#define IDC_EDIT_LENGTH                 1240
#define IDC_EDIT_CTRACEUP               1241
#define IDC_EDIT_GRAVITY                1241
#define IDC_EDIT_CTRACEDN               1242
#define IDC_EDIT_FLARE                  1242
#define IDC_EDIT_FACES                  1243
#define IDC_EDIT_RAND                   1243
#define IDC_EDIT_WIDTH                  1244
#define IDC_EDIT_BLUR                   1244
#define IDC_EDIT_DFACES                 1245
#define IDC_EDIT_FULLTIME               1248
#define IDC_EDIT_CCOLOR1                1249
#define IDC_STATIC_ANIEFF               1249
#define IDC_EDIT_ALPHATIME              1249
#define IDC_EDIT_CCOLOR2                1250
#define IDC_CHECK_FLAG1                 1250
#define IDC_EDIT_DEPTH                  1250
#define IDC_EDIT_CCOLOR3                1251
#define IDC_CHECK_FLAG4                 1251
#define IDC_EDIT_SIZE                   1251
#define IDC_EDIT_CCOLOR4                1252
#define IDC_CHECK_FLAG7                 1252
#define IDC_EDIT_VS1                    1252
#define IDC_CHECK_FLAG2                 1253
#define IDC_EDIT_VS2                    1253
#define IDC_CHECK_FLAG5                 1254
#define IDC_EDIT_VS3                    1254
#define IDC_CHECK_FLAG8                 1255
#define IDC_EDIT_VE1                    1255
#define IDC_CHECK_FLAG10                1256
#define IDC_EDIT_VE2                    1256
#define IDC_CHECK_FLAG11                1257
#define IDC_EDIT_VE3                    1257
#define IDC_CHECK_FLAG3                 1258
#define IDC_EDIT_DC1                    1258
#define IDC_CHECK_FLAG6                 1259
#define IDC_EDIT_DC2                    1259
#define IDC_CHECK_FLAG9                 1260
#define IDC_EDIT_DC3                    1260
#define IDC_EDIT_FRAME                  1261
#define IDC_EDIT_DC4                    1261
#define IDC_EDIT_FACT                   1262
#define IDC_EDIT_MAT1                   1263
#define IDC_EDIT_EFF                    1264
#define IDC_EDIT_MAT2                   1265
#define IDC_EDIT_FLAGS                  1265
#define IDC_EDIT_MAT3                   1266
#define IDC_EDIT_FRAME1                 1266
#define IDC_EDIT_MAT4                   1267
#define IDC_EDIT_FRAME2                 1267
#define IDC_EDIT_MAT5                   1268
#define IDC_EDIT_GNUM                   1268
#define IDC_EDIT_MAT6                   1269
#define IDC_EDIT_AMAX                   1269
#define IDC_CHECK_BUSE                  1269
#define IDC_EDIT_MAT7                   1270
#define IDC_EDIT_UNIT                   1270
#define IDC_EDIT_ATTRI                  1270
#define IDC_EDIT_MAT8                   1271
#define IDC_EDIT_DCOLOR1                1271
#define IDC_CHECK_GRAVITY               1271
#define IDC_EDIT_GCOL1                  1271
#define IDC_EDIT_MAT9                   1272
#define IDC_EDIT_DCOLOR2                1272
#define IDC_CHECK_FLARE                 1272
#define IDC_CHECK_EFLAG1                1272
#define IDC_EDIT_GCOL2                  1272
#define IDC_EDIT_MAT10                  1273
#define IDC_EDIT_DCOLOR3                1273
#define IDC_CHECK_EFLAG2                1273
#define IDC_EDIT_GCOL3                  1273
#define IDC_EDIT_MAT11                  1274
#define IDC_EDIT_DCOLOR4                1274
#define IDC_CHECK_EFLAG3                1274
#define IDC_EDIT_GCOL4                  1274
#define IDC_EDIT_MAT12                  1275
#define IDC_CHECK_EFLAG4                1275
#define IDC_EDIT_MAT13                  1276
#define IDC_CHECK_EFLAG5                1276
#define IDC_EDIT_MAT14                  1277
#define IDC_CHECK_EFLAG6                1277
#define IDC_EDIT_MAT15                  1278
#define IDC_CHECK_EFLAG7                1278
#define IDC_EDIT_MAT16                  1279
#define IDC_CHECK_EFLAG8                1279
#define IDC_EDIT_BIP1                   1280
#define IDC_CHECK_EFLAG9                1280
#define IDC_EDIT_BIP2                   1281
#define IDC_CHECK_AFLAG1                1284
#define IDC_CHECK_AFLAG2                1285
#define IDC_CHECK_AFLAG3                1286
#define IDC_CHECK_AFLAG4                1287
#define IDC_CHECK_AFLAG5                1288
#define IDC_CHECK_AFLAG6                1289
#define IDC_CHECK_AFLAG7                1290
#define IDC_CHECK_AFLAG8                1291
#define IDC_EDIT_TEX1                   1292
#define IDC_EDIT_TEX2                   1293
#define IDC_EDIT_TEX3                   1294
#define IDC_EDIT_COLOR                  1294
#define IDC_EDIT_TEX4                   1295
#define IDC_EDIT_POWER                  1295
#define IDC_EDIT_SPEC1                  1296
#define IDC_EDIT_SPEC2                  1297
#define IDC_EDIT_SPEC3                  1298
#define IDC_EDIT_SPEC4                  1299
#define IDC_EDIT_TEXT                   1300
#define IDC_LIST_MAT                    1301
#define IDC_CHECK_BFLAGS1               1302
#define IDC_CHECK_BFLAGS2               1303
#define IDC_CHECK_BFLAGS3               1304
#define IDC_CHECK_BFLAGS4               1305
#define IDC_CHECK_BFLAGS5               1306
#define IDC_CHECK_BFLAGS6               1307
#define IDC_CHECK_BFLAGS7               1308
#define IDC_CHECK_BFLAGS8               1309
#define IDC_BUTTON_ADD                  1310
#define IDC_BUTTON_EDIT                 1311
#define IDC_BUTTON_DEL                  1312
#define IDC_BUTTON_COPY                 1313
#define IDC_BUTTON_CLEAR                1314
#define IDC_BUTTON_AOK                  1315
#define IDC_BUTTON_ACAN                 1316
#define IDC_EFFUSE                      1317
#define IDC_EDIT_D1                     1318
#define IDC_EDIT_D2                     1319
#define IDC_EDIT_D3                     1320
#define IDC_EDIT_D4                     1321
#define IDC_EDIT_A1                     1322
#define IDC_EDIT_A2                     1323
#define IDC_EDIT_A3                     1324
#define IDC_EDIT_A4                     1325
#define IDC_EDIT_S1                     1326
#define IDC_EDIT_S2                     1327
#define IDC_EDIT_S3                     1328
#define IDC_EDIT_S4                     1329
#define IDC_EDIT_E1                     1330
#define IDC_EDIT_E2                     1331
#define IDC_EDIT_E3                     1332
#define IDC_EDIT_E4                     1333
#define IDC_EDIT_APOWER                 1334
#define IDC_EDIT_ATEX                   1335
#define IDC_EDIT_EMITTEX                1335
#define IDC_EDIT_AEFF                   1336
#define IDC_CHECK_AFLAG                 1336
#define IDC_EDIT_AWTIME                 1337
#define IDC_CHECK_BFLAGS9               1337
#define IDC_EDIT_APTIME                 1338
#define IDC_EDIT_AHEIGHT                1339
#define IDC_EDIT_AALPHA                 1340
#define IDC_CHECK_NFLAG1                1340
#define IDC_EDIT_TEXTURE                1341
#define IDC_EDIT_COL1                   1342
#define IDC_EDIT_SRCTEX1                1342
#define IDC_EDIT_SRCTEX2                1343
#define IDC_EDIT_MFLAG                  1344
#define IDC_EDIT_SRCTEX3                1344
#define IDC_EDIT_MBLEND                 1345
#define IDC_EDIT_D3TEX1                 1345
#define IDC_EDIT_MTNUM                  1346
#define IDC_EDIT_D3TEX2                 1346
#define IDC_EDIT_DIF1_1                 1347
#define IDC_EDIT_D3TEX3                 1347
#define IDC_CHECK_NFLAG2                1348
#define IDC_EDIT_DIF1_2                 1348
#define IDC_EDIT_DOTEX1                 1348
#define IDC_CHECK_NFLAG3                1349
#define IDC_EDIT_DIF2_1                 1349
#define IDC_EDIT_DOTEX2                 1349
#define IDC_CHECK_NFLAG4                1350
#define IDC_EDIT_DIF2_2                 1350
#define IDC_EDIT_DOTEX3                 1350
#define IDC_CHECK_NFLAG5                1351
#define IDC_EDIT_DIF1_3                 1351
#define IDC_EDIT_COLOROP                1351
#define IDC_CHECK_NFLAG6                1352
#define IDC_EDIT_DIF1_4                 1352
#define IDC_CHECK_NFLAG7                1353
#define IDC_EDIT_DIF2_3                 1353
#define IDC_CHECK_NFLAG8                1354
#define IDC_EDIT_DIF2_4                 1354
#define IDC_CHECK_NFLAG9                1355
#define IDC_EDIT_TEX1_1                 1355
#define IDC_CHECK_NFLAG10               1356
#define IDC_EDIT_TEX1_2                 1356
#define IDC_CHECK_NFLAG11               1357
#define IDC_EDIT_TEX2_1                 1357
#define IDC_CHECK_NFLAG12               1358
#define IDC_EDIT_TEX2_2                 1358
#define IDC_CHECK_NFLAG13               1359
#define IDC_EDIT_UV1_1                  1359
#define IDC_CHECK_NFLAG14               1360
#define IDC_EDIT_UV1_2                  1360
#define IDC_CHECK_NFLAG15               1361
#define IDC_EDIT_UV2_1                  1361
#define IDC_EDIT_COL2                   1362
#define IDC_EDIT_UV2_2                  1362
#define IDC_EDIT_COL3                   1363
#define IDC_EDIT_TEXTURE1               1363
#define IDC_EDIT_COL4                   1364
#define IDC_EDIT_TEXTURE2               1364
#define IDC_COMBO_COLOP                 1365
#define IDC_CHECK_AMFLAG1               1367
#define IDC_CHECK_AMFLAG2               1368
#define IDC_EDIT_FTIME                  1370
#define IDC_EDIT_SCRCOLOR               1371
#define IDC_EDIT_AMCOLOR1               1372
#define IDC_EDIT_AMCOLOR2               1373
#define IDC_CHECK_D3FLAG1               1373
#define IDC_EDIT_AMCOLOR3               1374
#define IDC_CHECK_D3FLAG2               1374
#define IDC_EDIT_AMCOLOR4               1375
#define IDC_CHECK_D3FLAG3               1375
#define IDC_CHECK_D3FLAG4               1376
#define IDC_CHECK_D3FLAG5               1377
#define IDC_CHECK_D3FLAG6               1378
#define IDC_COMBO_D3OP1                 1379
#define IDC_COMBO_D3OP2                 1380
#define IDC_COMBO_D3OP3                 1381
#define IDC_CHECK_MTFLAG1               1383
#define IDC_CHECK_MTFLAG2               1384
#define IDC_CHECK_MTFLAG3               1385
#define IDC_CHECK_MTFLAG4               1386
#define IDC_CHECK_MTFLAG5               1387
#define IDC_CHECK_MTFLAG6               1388
#define IDC_CHECK_MTFLAG7               1389
#define IDC_CHECK_MTFLAG8               1390
#define IDC_CHECK_MTFLAG9               1391
#define IDC_CHECK_MTFLAG10              1392
#define IDC_CHECK_MTFLAG11              1393
#define IDC_EDIT_MDIF1_1                1395
#define IDC_EDIT_MDIF1_2                1396
#define IDC_EDIT_MDIF1_3                1397
#define IDC_EDIT_MDIF1_4                1398
#define IDC_EDIT_MDIF2_1                1399
#define IDC_EDIT_MDIF2_2                1400
#define IDC_EDIT_MDIF2_3                1401
#define IDC_EDIT_MDIF2_4                1402
#define IDC_EDIT_MTEX1_1                1403
#define IDC_EDIT_MTEX1_2                1404
#define IDC_EDIT_GFLAG                  1404
#define IDC_EDIT_MTEX1                  1405
#define IDC_SP2FLAG1                    1405
#define IDC_EDIT_MTEX2                  1406
#define IDC_EDIT_MTEX                   1407
#define IDC_EDIT_MTEXUV1_1              1408
#define IDC_CHECK_TFLAG1                1408
#define IDC_EDIT_MTEXUV1_2              1409
#define IDC_EDIT_TSIZE                  1409
#define IDC_EDIT_MTEX2_1                1410
#define IDC_EDIT_TSIZEADD               1410
#define IDC_EDIT_INTE                   1410
#define IDC_EDIT_MTEX2_2                1411
#define IDC_EDIT_TTEX                   1411
#define IDC_EDIT_SPE                    1411
#define IDC_CHECK_PSIZE1                1411
#define IDC_EDIT_MTEXUV2_1              1412
#define IDC_EDIT_OTEX                   1412
#define IDC_CHECK_PSIZE2                1412
#define IDC_EDIT_MTEXUV2_2              1413
#define IDC_CHECK_PSIZE3                1413
#define IDC_CHECK_PSIZE4                1414
#define IDC_CHECK_PSIZE5                1415
#define IDC_CHECK_PSIZE6                1416
#define IDC_CHECK_PSIZE7                1417
#define IDC_EDIT_PPEC                   1418
#define IDC_EDIT_RRANGE                 1419
#define IDC_EDIT_DCOL1                  1419
#define IDC_EDIT_LVLIFE1                1419
#define IDC_EDIT_PCOLOR1                1420
#define IDC_EDIT_DCOL2                  1420
#define IDC_EDIT_LVLIFE2                1420
#define IDC_EDIT_VSIZE1                 1421
#define IDC_EDIT_DCOL3                  1421
#define IDC_EDIT_LVSIZE1                1421
#define IDC_EDIT_VSIZE2                 1422
#define IDC_EDIT_DCOL4                  1422
#define IDC_EDIT_LVSIZE2                1422
#define IDC_EDIT_VSIZE3                 1423
#define IDC_EDIT_VLIFE1                 1423
#define IDC_EDIT_LVSIZE3                1423
#define IDC_EDIT_LMIN                   1424
#define IDC_EDIT_VLIFE2                 1424
#define IDC_EDIT_SCALE_X1               1424
#define IDC_EDIT_LMAX                   1425
#define IDC_EDIT_VROT1                  1425
#define IDC_EDIT_SCALE_X2               1425
#define IDC_EDIT_ROT1                   1426
#define IDC_EDIT_VROT2                  1426
#define IDC_EDIT_LSHAKE                 1426
#define IDC_EDIT_ROT2                   1427
#define IDC_EDIT_LSEQ_COL               1427
#define IDC_EDIT_VEL1                   1428
#define IDC_EDIT_LSEQ_ROW               1428
#define IDC_EDIT_VEL2                   1429
#define IDC_EDIT_LCLEN                  1429
#define IDC_EDIT_SCOL                   1430
#define IDC_EDIT_SROW                   1431
#define IDC_EDIT_PTEXT                  1432
#define IDC_EDIT_CLE                    1432
#define IDC_BUTTON_PADD                 1433
#define IDC_EDIT_TXBONE                 1433
#define IDC_BUTTON_PEDIT                1434
#define IDC_EDIT_TXTEXT                 1434
#define IDC_BUTTON_PDEL                 1435
#define IDC_BUTTON_BLEDIT               1435
#define IDC_BUTTON_PMUP                 1436
#define IDC_BUTTON_BLDEL                1436
#define IDC_BUTTON_PMDN                 1437
#define IDC_BUTTON_BLUP                 1437
#define IDC_BUTTON_PCLR                 1438
#define IDC_EDIT_PX                     1439
#define IDC_BUTTON_BLDN                 1439
#define IDC_EDIT_PY                     1440
#define IDC_EDIT_PZ                     1441
#define IDC_LIST_VEC                    1442
#define IDC_EDIT_PCOLOR2                1443
#define IDC_CHECK_BPFLAG1               1443
#define IDC_EDIT_PCOLOR3                1444
#define IDC_CHECK_BPFLAG2               1444
#define IDC_EDIT_PCOLOR4                1445
#define IDC_CHECK_BPFLAG3               1445
#define IDC_BUTTON_POK                  1446
#define IDC_CHECK_BPFLAG4               1446
#define IDC_BUTTON_PCAN                 1447
#define IDC_CHECK_BPFLAG5               1447
#define IDC_CHECK_BPFLAG6               1448
#define IDC_CHECK_BPFLAG7               1449
#define IDC_BUTTON_BLOK                 1450
#define IDC_BUTTON_BLCAN                1451
#define IDC_EDIT_VSIZE1_1               1452
#define IDC_EDIT_VSIZE1_2               1453
#define IDC_EDIT_VSIZE1_3               1454
#define IDC_EDIT_BONEN                  1455
#define IDC_EDIT_VVEL1                  1456
#define IDC_EDIT_VVEL2                  1457
#define IDC_EDIT_VVEL3                  1458
#define IDC_BUTTON_BLADD                1458
#define IDC_EDIT_VLOC1                  1459
#define IDC_BUTTON_BLCLR                1459
#define IDC_EDIT_VLOC2                  1460
#define IDC_CHECK_BVERT                 1460
#define IDC_EDIT_VLOC3                  1461
#define IDC_EDIT_VVR1                   1461
#define IDC_EDIT_VVR2                   1462
#define IDC_CHECK_UCFLAG1               1462
#define IDC_EDIT_VVR3                   1463
#define IDC_EDIT_UCOL1                  1463
#define IDC_EDIT_UCOL2                  1464
#define IDC_EDIT_NFLAG                  1464
#define IDC_EDIT_UCOL3                  1465
#define IDC_CHECK_L2FLAG1               1465
#define IDC_EDIT_UCOL4                  1466
#define IDC_CHECK_L2FLAG2               1466
#define IDC_CHECK_L2FLAG3               1467
#define IDC_CHECK_L2FLAG4               1468
#define IDC_EDIT_OCOLOR                 1469
#define IDC_EDIT_LCOL1_1                1470
#define IDC_EDIT_LCOL1_2                1471
#define IDC_EDIT_LCOL1_3                1472
#define IDC_EDIT_LCOL1_4                1473
#define IDC_EDIT_LCOL2_1                1474
#define IDC_EDIT_LCOL2_2                1475
#define IDC_EDIT_LCOL2_3                1476
#define IDC_EDIT_LCOL2_4                1477
#define IDC_EDIT_SCALE_Y1               1478
#define IDC_EDIT_SCALE_Y2               1479
#define IDC_EDIT_SCALE_Y3               1480
#define IDC_CHECK_BCAM                  1481
#define IDC_EDIT_DIST_MIN               1482
#define IDC_EDIT_DIST_MAX               1483
#define IDC_EDIT_TEXR_MIN               1484
#define IDC_EDIT_TEXR_MAX               1485
#define IDC_EDIT_L2TEX1                 1486
#define IDC_EDIT_L2TEX2                 1487
#define IDC_LIST_LINE                   1488
#define IDC_BUTTON_L2ADD                1489
#define IDC_BUTTON_L2EDIT               1490
#define IDC_BUTTON_L2DEL                1491
#define IDC_BUTTON_L2CLR                1492
#define IDC_BUTTON_L2OK                 1493
#define IDC_BUTTON_L2CAN                1494
#define IDC_ARFLAG1                     1494
#define IDC_EDIT_ARTEX                  1495
#define IDC_EDIT_ARCOLOR1               1496
#define IDC_EDIT_ARCOLOR2               1497
#define IDC_EDIT_ARCOLOR3               1498
#define IDC_EDIT_ARCOLOR4               1499
#define IDC_EDIT_ARSEC_COL              1500
#define IDC_EDIT_ARSEC_ROW              1501
#define IDC_EDIT_TSPD_1                 1502
#define IDC_EDIT_TSPD_2                 1503
#define IDC_EDIT_MVSIZE_MIN_1           1504
#define IDC_EDIT_LTIME_1                1505
#define IDC_EDIT_MVSIZE_MIN_2           1506
#define IDC_EDIT_MVSIZE_MAX_1           1507
#define IDC_EDIT_MVSIZE_MAX_2           1508
#define IDC_EDIT_LTIME_2                1509
#define IDC_EDIT_RTIME_1                1510
#define IDC_EDIT_RTIME_2                1511
#define IDC_LIST_AR                     1512
#define IDC_BUTTON_ARADD                1513
#define IDC_BUTTON_ARDEL                1514
#define IDC_BUTTON_AREDIT               1515
#define IDC_BUTTON_ARCLR                1516
#define IDC_BUTTON_ARCAN                1517
#define IDC_EDIT_RVPOS1                 1518
#define IDC_EDIT_RVPOS2                 1519
#define IDC_EDIT_RVPOS3                 1520
#define IDC_EDIT_RBONE                  1521
#define IDC_EDIT_RNOR1                  1522
#define IDC_EDIT_RNOR2                  1523
#define IDC_EDIT_RNOR3                  1524
#define IDC_EDIT_RSIZE_1                1525
#define IDC_EDIT_RSIZE_2                1526
#define IDC_EDIT_RMESH                  1527
#define IDC_EDIT_RLTIME                 1528
#define IDC_EDIT_RRTIME                 1529
#define IDC_EDIT_RROT                   1530
#define IDC_EDIT_TEXSPEED               1531
#define IDC_EDIT_RTIME                  1532
#define IDC_EDIT_RTEXTIME               1533
#define IDC_RB_ALIVE                    1534
#define IDC_BUTTON_AROK                 1535
#define IDC_BUTTON_AROK2                1536
#define IDC_BUTTON_VPOS                 1536
#define IDC_LIST_SCALE                  1536
#define IDC_BTN_SC_ADD                  1537
#define IDC_BTN_SC_EDIT                 1538
#define IDC_BTN_SC_DEL                  1539
#define IDC_BTN_SC_CLEAR                1540
#define IDC_LIST_SCDATA                 1541
#define IDC_BTN_SCM_ADD                 1542
#define IDC_BTN_SCM_EDIT                1543
#define IDC_BTN_SCM_DEL                 1544
#define IDC_BTN_SCM_CLEAR               1545
#define IDC_EDIT_SCNAME                 1546
#define IDC_EDIT_SCM_KEY                1547
#define IDC_EDIT_SCM_SCALE              1548
#define IDC_STATIC_CREDITS              1548
#define IDC_BTN_SC_OK                   1549
#define IDC_EDIT_HISTORY                1549
#define IDC_BTN_SC_CAN                  1550
#define IDC_BTN_SCM_OK                  1551
#define IDC_BTN_SC_CAN2                 1552
#define IDC_BTN_SCM_CAN                 1552
#define IDC_COMBO_HEXTYPE               1557
#define IDC_BUTTON_HEXCNV               1558
#define IDC_COMBO_CNVTYPE               1559
#define IDC_COMBO_CNVMODE               1560
#define IDC_EDIT_IN                     1561
#define IDC_EDIT_OUT                    1562
#define IDC_BUTTON_IN                   1563
#define IDC_BUTTON_OUT                  1564
#define IDC_BUTTON_CONVERT              1565
#define IDC_BUTTON_EQUAL                1566

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1567
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
